name: Create Github Release
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version being released'
        required: true
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'

jobs:
    test:
        name: Test
        runs-on: ubuntu-18.04
        env:
          PRE_RELEASE: false    
        steps:

            - name: Install Gren
              run: npm install github-release-notes -g

            - name: Checkout Code with Ref '${{ github.ref }}'
              uses: actions/checkout@v2
              
            - name: Determine Release Type
              if: "contains(github.event.inputs.release-version, 'RC')"
              run: |
                echo "This is a pre-release. Setting environment variable 'PRE_RELEASE' to true"
                echo "PRE_RELEASE=true" >> $GITHUB_ENV
            
            - name: Create GitHub Release
              run: |
                echo "PRE_RELEASE=$PRE_RELEASE"
                ./.github/scripts/create-github-release.sh ${{ github.event.inputs.release-version}} ${{ github.event.inputs.branch}} $GITHUB_REPOSITORY ${{ secrets.ACCESS_TOKEN }} ${{ env.PRE_RELEASE }}
              
            - name: Generate Release Notes
              run: gren release --token=${{ secrets.GITHUB_TOKEN }} --override --debug --data-source=milestones --milestone-match="Release ${{ github.event.inputs.release-version }}"