name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version being released'
        required: true
jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      IS_PRE_RELEASE: false
    steps:
      - name: Log Metadata
        env:
          abc: "${{github.event.inputs.release-version}}"
          def: "${{env.IS_PRE_RELEASE}}"
          ghi: '-Dmaven.wagon.httpconnectionManager.maxTotal=30 -Dmaven.wagon.http.retryHandler.count=5 --no-transfer-progress'
        run: |
          echo "${abc}"
          echo "${def}"
          echo "${ghi}"
